### ISSUE TITLE
Rawlist

### ISSUE THREAD

**Issue by adam-diakite-ebi** [Beknaizer/OCT-Retinal-Layer-Segmenter#2]
Hello and thank you very much for this project.

I have a problem though: what is rawlist and why isn't it initialised ? I have an error when reaching this point.
Thanks again.

**Comment by beasygo1ng** [comment]
Hello! I am very glad that my code and experience have been useful to others, especially you. I have updated the code, you can check it, I hope I have solved your problem and I am very grateful that you noticed the error. Good luck in your endeavors!

**Comment by beasygo1ng** [comment]
Have I solved your problem? Can you give response please.
