### ISSUE TITLE
"Rawlist" in json_mask_reading?

### ISSUE THREAD

**Issue by shahud1** [Beknaizer/OCT-Retinal-Layer-Segmenter#3]
How did you get the "Rawlist" in json_mask_reading? I am unable to go forward from that point onwards. Getting error message like:

NameError:  name 'Rawlist' is not defined.

This is in the file name json_mask_reading.ipynb

**Comment by Beknaizer** [comment]
Hello ! Yes, it seems I just deleted that line by accident) can you check it now?

**Comment by Beknaizer** [comment]
@

**Comment by beasygo1ng** [comment]
Hello ! Yes, it seems I just deleted that line by accident) can you check it now?
