### ISSUE TITLE
Question regarding amount of data

### ISSUE THREAD

**Issue by CMaldonado1** [Beknaizer/OCT-Retinal-Layer-Segmenter#5]
Hi there,

I have a quick question. I came across information that you used 25 healthy patients for your training and testing. However, I'm a bit unclear on whether all 25 were used for both training and testing or if they were only used for training. Could you please clarify this for me? 

Thank you for providing your code! It has proven to be quite valuable for me.

BW, 
Cynthia

**Comment by beasygo1ng** [comment]
Hi!  
If i am not mistaken, i used 25 only for training. For testing i was annotated another batch of data
